# **Курс "Програмування на мові Python"**

## **Практичне зайняття №9**

### Тема: "Робота з функціями. Локальні та глобальні змінні"

### **Завдання 1 (3 бали)**

**Підрахувати визначник матриці, використовуючи правило перестановок.**

Функція random_matrix() призначена для створення квадратної матриці випадкових чисел. Її змінювати непотрібно.

Приклад використання методу permutations() для створення списку перестановок також подається у комірці з кодом.

1) Створити 3 функції: функцію створення списку перестановок, функцію підрахунку добутків та функцію підрахунку загальної суми.

2) Кожна функція має супроводжуватись рядком документації, що буде коротко описувати її призначення.

3) Розмірність квадратної матриці має вводитись користувачем з клавіатури. Підрахунки виконувати лише в тому разі, якщо користувач введе ціле додатне число.

4) Загальний результат повинен підраховуватись за допомогою композиції функцій.

За бажанням можна перевірити правильність роботи програми за допомогою функції np.linalg.det(a).

In [3]:
import numpy as np
import itertools

def random_matrix(dim):
    """
    The function generates dim x dim array of integers
    between 0 and 10.
    """
    matrix = np.random.randint(10, size = (dim, dim))
    return matrix

#Example of using permutations() method
t = list(itertools.permutations('123', 3))
ok = False
while not ok:
    try:
        dimension = int(input('Input dimension of the matrix:'))
        if dimension<1:
            print('You input negative value of dimension. Try again.')
        else:
            ok = True
    except:
        print('You entered not integer number. Try again.')
matrix = random_matrix(dimension)
print('The random matrix is', '\n', matrix)
def permutations(n):
    """
    The first function find all possible permutations.
    """
    index = []
    for i in range(0,dimension):
        index.append(i)
    p = list(itertools.permutations([str(i) for i in range(1,dimension+1)], dimension))
    return p   
def multiple(m):
    """
    The second function calculates for each permutation 
    its sign and the corresponding product of elements 
    from the matrix.
    """
    global matrix
    mul=[]
    for pi in m:
        p=1
        n=0
        for j in range(len(pi)):
            ok = True
            u = j
            while ok:
                if u==len(pi):
                    ok = False
                elif (pi[j]>pi[u]) and (pi[j]!=pi[u]): 
                    p*=-1
                    u+=1
                else:
                    u+=1
        for i in range(len(pi)):
            p = p*int(matrix[i][int(pi[i])-1])
        mul.append(pow(-1,n)*p)
    return mul
def summ(det):
    """
    The third function sums the received products with 
    the correct sign.
    """   
    det = sum(det)
    return det

print('The determinant of this matrix is:', summ(multiple(permutations(matrix))))
print('Сheck the correctness of the program using the function np.linalg.det (a).:', round(np.linalg.det(matrix)))


The random matrix is 
 [[2 0 1 7 7]
 [7 4 6 0 7]
 [6 7 0 4 9]
 [3 4 7 5 1]
 [9 3 0 2 5]]
The determinant of this matrix is: 20566
Сheck the correctness of the program using the function np.linalg.det (a).: 20566
